### ISSUE TITLE
No link in Developer Documentation

### ISSUE THREAD

**Issue by Ankitaheroorkar** [AnanseGroup/map-of-innovation#36]
There is no link in API in Developer Documentation
http://52.197.65.30:5000/docs/developer
Tested in Firefox for Ubuntu canonical-1.0

**Comment by chinmayisk** [comment]
[SEE BELOW]
more details on what the link is ?  
Is there a screen shot ?

**Comment by annawb** [comment]
The current links on this page aren't very obvious...  underline all the links on this page so they're clearly marked.

Additional missing links:
- Datafields: "join the API discussion on our Github here" should link to https://github.com/AnanseGroup/map-of-innovation
- API: "Click here to check out our REST API" should link to https://github.com/AnanseGroup/map-of-innovation (unless there's a specific API link?)
- API: "click here to get involved with Maker.json" should link to https://github.com/rrbaker/maker.json
- " join the discussion forum here" should link to https://docs.google.com/document/d/1U9BwfkqsDpekBjB9DkHUnKrLJigaIYWK0HX6zuM9Nv0/edit

**Comment by annawb** [comment]
Duplicate bug as #48 
Additional info:
Is there a webpage with the API that you can link to, such as this one for fablabs.io: https://api.fablabs.io/v0/labs.json

Or maybe this should link to a specific Github page? I'm not exactly sure what people will be expecting if they want to find our API... Anyway, marking as Top because the Germans seem to REALLY care about broken links... if we don't have the API up already, just change the API-related text to "We'll upload our REST API soon, but in the meantime please click here to get involved with Maker.json...."

**Comment by chinmayisk** [comment]
We dont have a api page up, we need time to document. can you give me exact text to put up in that case ?

**Comment by chinmayisk** [comment]
marking as fixed
